### ISSUE TITLE
Database settings for setup

### ISSUE THREAD

**Issue by evandrojr** [ThisIsQasim/TastyIgniter#2]
Hi,

Nice work!

 I've tried at the 'Database Settings', page that:

```
  MYSQL_DATABASE: tastydb
  MYSQL_USER: tastyuser
  MYSQL_PASSWORD: tastypass
```

But it did not work. What is the host?  I am missing anything?

Thanks!

**Comment by aeksco** [comment]
@evandrojr See attached image - you have to set the hostname attribute to `mysql` instead of the default `localhost`

![screenshot from 2018-02-28 14-26-25](https://user-images.githubusercontent.com/4616233/36808571-78fe5e54-1c93-11e8-93ff-adcd395d6ec4.png)

**Comment by lalitnandandiwakar** [comment]
what database setting

**Comment by ThisIsQasim** [comment]
If you are using docker-compose then the hostname, username and password should be tastydb, tastyuser and tastypass. These settings should have been prefilled. Please check and report back if it doesn’t work.

**Comment by lalitnandandiwakar** [comment]
Not Working Plz help me 
i try to install in aws

**Comment by ThisIsQasim** [comment]
I just verified that the mentioned settings do indeed work. You just have to give the db container a few minutes to setup the user and a database before you can connect to it. I’d suggest you wait a few minutes after you run `docker-compose up -d` before opening the portal. Then use the following credentials.
Database: tastydb
Hostname: tasty_db
Username: tastyuser
Password: tastypass

Though you really should change these credentials in the `docker-compose.yml` file

On 15-May-2018, at 12:32 AM, Lalit Nandan Diwakar <notifications@github.com<mailto:notifications@github.com>> wrote:


Not Working Plz help me

**Comment by lalitnandandiwakar** [comment]
i am face this error 

![image](https://user-images.githubusercontent.com/11966970/40036319-623fd91e-5824-11e8-885c-4f71e5da2578.png)

**Comment by lalitnandandiwakar** [comment]
any suggestion for me or any alternate way

**Comment by aeksco** [comment]
@lalitnandandiwakar Your `Hostname` shouldn't be `tasty_db` - try `mysql` instead

**Comment by ThisIsQasim** [comment]
I have pushed a new commit. The new settings are as follows and should work. As always you can (and should) change these in the `docker-compose.yml` file. Also remember that the mariadb container takes a few seconds to setup a database before you can use it so give it a minute or two before you access the UI.

`MYSQL_HOSTNAME=db`
`MYSQL_DATABASE=tastyigniter`
`MYSQL_USER=tastyigniter`
`MYSQL_PASSWORD=somepassword`

**Comment by ThisIsQasim** [comment]
I have also fixed the entrypoint script so it should automatically fill in the correct values

**Comment by luhgit** [comment]
Hi, I have built the image from the Dockerfile you provided. And the Entrypoint script auto fills the credentials but it still throws the same error:

Database connection was unsuccessful, please make sure the database server, username and password is correct.

Any idea? why could it be?

Thanks.

**Comment by ThisIsQasim** [comment]
@luhgit Are you using the docker-compose file? If so just give it a few minutes after you bring the db container up. Try running the setup once the db is up and running.

**Comment by luhgit** [comment]
@ThisIsQasim: I actually waited and usually on my current machine it is almost instant. I have attached the screenshot of all the resources. But error still persists. I also modified your actual script a tiny bit as Dockerfile did not work out of the box due to some depreciation of php libraries. Do you spot some discrepancy?

Thanks.

![image](https://user-images.githubusercontent.com/8448270/107871591-37cf7700-6ea3-11eb-8b71-28d34e681813.png)

![image](https://user-images.githubusercontent.com/8448270/107871600-5170be80-6ea3-11eb-91a6-98f18a442628.png)

![image](https://user-images.githubusercontent.com/8448270/107871610-69e0d900-6ea3-11eb-9996-19f1aca4cc14.png)

![image](https://user-images.githubusercontent.com/8448270/107871618-7bc27c00-6ea3-11eb-99e4-49e8c805ea74.png)

![image](https://user-images.githubusercontent.com/8448270/107871628-9d236800-6ea3-11eb-86c6-9742d1f34af7.png)

**Comment by ThisIsQasim** [comment]
Can you check if you can actually connect to the database with the credentials you are entering in tastyigniter?

**Comment by luhgit** [comment]
I actually tried to connect locally via mysql command even inside of the container. but did get into the database. 

![image](https://user-images.githubusercontent.com/8448270/107879400-da561d00-6ed8-11eb-98f8-df2ed25a367b.png)

**Comment by ThisIsQasim** [comment]
Looks like your db container doesn’t have the user. You can either do that by recreating that container on an empty volume or create a user by logging in with the root user.

**Comment by luhgit** [comment]
Actually, Now I have realized the error. Mariadb does not create a new user if a volume has already been created for a certain docker-compose file. I had to remove also the volume and then rerun and this time it works like a charm.

Thanks for hint @ThisIsQasim 

so instead of:

`docker-compose down`

one must do:

`docker-compose down -v`

(If it helps someone else)

**Comment by ThisIsQasim** [comment]
Yes. The mariadb container will not create a user if there is data on the volume.
